server:
  port: 8080

management:
  server.port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
      cache:
        time-to-live: 5s
  health:
    defaults:
      enabled: false

logging:
  file:
    path: ${user.dir}/out
